### ISSUE TITLE
Dependency on 'clone'

### ISSUE THREAD

**Issue by vitalets** [sindresorhus/node-defaults#3]
Thanks for the useful package! Is it necessary to depend on [clone](https://www.npmjs.com/package/clone)?
It adds [24.kb (7kb gzipped)](https://bundlephobia.com/result?p=clone@2.1.1) to package size, but looks a bit overhead as cloning `maps, sets, promises etc` is edge case for defaults.

**Comment by sindresorhus** [comment]
It no longer has any dependencies or clones objects: https://github.com/sindresorhus/node-defaults/releases/tag/v2.0.0
